### ISSUE TITLE
stardb-exporter.exe is reported as a torjan virus(Trojan/Agent.bkq） 

### ISSUE THREAD

**Issue by minecraft-mu-xiao** [juliuskreutz/stardb-exporter#5]
I don't know if I have download the right file,can you help me?
![image](https://github.com/juliuskreutz/stardb-exporter/assets/70486010/38daa567-db84-4222-a820-fc85756bce5d)
MD5 code of exe is b2e9a4a832c9f3ba82d5e7504dd3f146

**Comment by juliuskreutz** [comment]
Can confirm md5sum is `b2e9a4a832c9f3ba82d5e7504dd3f146` and sha256sum is `8362932c58f1fe5f0d3e9c951298a07f6dbfb1bda11e0d0877dbc0008e61b6b8`

Since a windows certificate is expensive I don't have one.

And without a certificate any program that captures your network requests (which is what the program does) will be recognized as a trojan.

The exe gets build from the source code directly if you wanna look at it.
